- name: remove ec2 instance
  hosts: all
  gather_facts: false
  connection: local
  vars:
    ansible_ssh_password: ''
  become: no
  vars_files:
    - mssql-nodes-ec2.yml

  roles:
    - role: ansible-role-ec2
      role_action: deprovision
      delegate_to: localhost
      run_once: yes

- hosts: localhost
  become: no
  tasks:
    - name: get ec2 instance information
      ec2_instance_info:
        region: "{{ ec2_region }}"
        filters:
          vpc-id: "{{ ec2_vpc_id }}"
          "tag:app": mssql-demo
      register: ec2_instances

    - name: terminate instances
      ec2:
        region: "{{ ec2_region }}"
        state: "absent"
        instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"