- hosts: all
  become: yes
  tasks:
    - name: set repos for 7.x
      set_fact:
        repo_channels:
          - rhel-7-server-rpms
          - rhel-7-server-rh-common-rpms
          - rhel-7-server-extras-rpms
          - rhel-7-server-aus-optional-rpms
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

    - name: set repos for 8.x
      set_fact:
        repo_channels:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-supplementary-rpms
          - rhel-8-for-x86_64-appstream-rpms
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 8

    - block:
        - include_role:
            name: "{{ role_name }}"
          loop_control:
            loop_var: role_name
          loop:
            - oatakan.rhn
            - oatakan.rhel_upgrade

      always:

        - include_role:
            name: oatakan.rhn
          vars:
            role_action: unregister

      when: ansible_distribution == 'RedHat'